### ISSUE TITLE
Issues with the mogrify command

### ISSUE THREAD

**Issue by metakermit** [petrosgk/Kaggle-Carvana-Image-Masking-Challenge#16]
Getting a lot of these messages after the `mogrify` step. Don't know if this is normal?

```
mogrify: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
```

The majority of the pngs seem to be generated…

**Comment by petrosgk** [comment]
The warning is `libpng` complaining about the embedded ICC profile in the images but it doesn't cause any problems. If you want to get rid of the warning you can strip the metadata from the images like this:

```
apt-get install exiftool
exiftool -overwrite_original -all= *
```

**Comment by jrfiedler** [comment]
I got rid of the messages by adding `-colorspace Gray` to the command:

    mogrify -format png -colorspace Gray *.gif

**Comment by metakermit** [comment]
Great, thanks!
