### ISSUE TITLE
number of classes

### ISSUE THREAD

**Issue by maylad31** [petrosgk/Kaggle-Carvana-Image-Masking-Challenge#20]
Hi, 
I was trying ti understand your code. Does no of classes equal to channels in the masks? Thanks for your help.

**Comment by petrosgk** [comment]
Yes.

**Comment by maylad31** [comment]
Hi,just one more thing what if i want to do multiclass segmentation.

**Comment by petrosgk** [comment]
You can treat each class as a channel, e.g. if you've got 3 classes then num_channels = 3 and your target should have dimensions (width, height, 3) where each channel is one class.

Have a look at this as well: 
https://stackoverflow.com/questions/43900125/how-to-implement-multi-class-semantic-segmentation

**Comment by maylad31** [comment]
Hi,thanks your code was nice and easy. You may close this issue.
