### ISSUE TITLE
something wrong with my code? i just following your code,3ks

### ISSUE THREAD

**Issue by Nandayang** [petrosgk/Kaggle-Carvana-Image-Masking-Challenge#5]
ValueError                                Traceback (most recent call last)
<ipython-input-20-778161543675> in <module>()
      5                     callbacks=callbacks,
      6                     validation_data=valid_generator(),
----> 7                     validation_steps=np.ceil(float(len(ids_valid_split)) // float(batch_size)))

/home/yang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     86                 warnings.warn('Update your `' + object_name +
     87                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 88             return func(*args, **kwargs)
     89         wrapper._legacy_support_signature = inspect.getargspec(func)
     90         return wrapper

/home/yang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_q_size, workers, pickle_safe, initial_epoch)
   1875                                          'a tuple `(x, y, sample_weight)` '
   1876                                          'or `(x, y)`. Found: ' +
-> 1877                                          str(generator_output))
   1878                     if len(generator_output) == 2:
   1879                         x, y = generator_output

ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

**Comment by petrosgk** [comment]
Have you converted the train masks to .png?

**Comment by Nandayang** [comment]
@petrosgk i have changed the 'png' to 'gif' in your code instead of converted the mask to .png. Wondering if it works.

**Comment by petrosgk** [comment]
Yes OpenCV doesn't support .gif, that's why I say you must convert the masks to .png in the readme. Glad you solved the issue.
